### ISSUE TITLE
Fatal error doesn't lead to a non-zero exit code

### ISSUE THREAD

**Issue by kasium** [reverbc/pylint-pytest#25]
**Describe the bug**
If the fatal error `cannot-enumerate-pytest-fixtures` is raised, pylint exists with a 0.

**To Reproduce**
See #24 for all details.

Also, use the following toml

```toml
[tool.pylint.master]
load-plugins = [
    "pylint_pytest"
]

[tool.pylint."messages control"]
disable = ["all"]
enable = ["cannot-enumerate-pytest-fixtures"]
```

pylint output
```bash
(venv) ~/git/empty_test # pylint x.py test_a.py
************* Module test_a
test_a.py:1:0: F6401: pylint-pytest plugin cannot enumerate and collect pytest fixtures. Please run `pytest --fixtures --collect-only path/to/current/module.py` and resolve any potential syntax error or package dependency issues (cannot-enumerate-pytest-fixtures)
(venv) ~/git/empty_test # echo $?
0
```

**Expected behavior**
Pylint should exit with a 1.
